name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install torch==2.2.0+cpu --extra-index-url https://download.pytorch.org/whl/cpu
          pip install transformers fastapi uvicorn pydantic httpx pytest

      - name: Run tests
        run: pytest tests/ -v

      - name: Build Docker image
        run: docker build -t sentiment-api .